# docker-compose.wordpress.yml
# Extends the WordPress service with specific PHP configuration via WP_CONFIG_EXTRA.

# version: '3.8'

services:
  wordpress:
    volumes:
      - ${WP_PHP_SRC_DIR}/wp-config.php:/var/www/html/wp-config.php
